-- Membatalkan 000033.
-- Index dibuang; FK users.role_id dikembalikan ke bentuk tunggal.
DROP INDEX IF EXISTS idx_users_role;
DROP INDEX IF EXISTS idx_activities_customer;
DROP INDEX IF EXISTS idx_activities_deal;
DROP INDEX IF EXISTS idx_advance_repayments_payslip;
DROP INDEX IF EXISTS idx_channel_orders_sale;
DROP INDEX IF EXISTS idx_channel_stock_syncs_channel;
DROP INDEX IF EXISTS idx_channels_price_list;
DROP INDEX IF EXISTS idx_customers_price_list;
DROP INDEX IF EXISTS idx_deals_customer;
DROP INDEX IF EXISTS idx_deals_lead_source;
DROP INDEX IF EXISTS idx_deals_pipeline;
DROP INDEX IF EXISTS idx_deferred_revenue_entries_tenant;
DROP INDEX IF EXISTS idx_employee_advances_cash_movement;
DROP INDEX IF EXISTS idx_invoice_items_invoice;
DROP INDEX IF EXISTS idx_invoice_items_product;
DROP INDEX IF EXISTS idx_invoices_customer;
DROP INDEX IF EXISTS idx_invoices_project;
DROP INDEX IF EXISTS idx_invoices_quotation;
DROP INDEX IF EXISTS idx_invoices_sale;
DROP INDEX IF EXISTS idx_payroll_adjustments_origin_period;
DROP INDEX IF EXISTS idx_payslip_lines_rule;
DROP INDEX IF EXISTS idx_payslips_employee;
DROP INDEX IF EXISTS idx_product_prices_variant;
DROP INDEX IF EXISTS idx_products_unit;
DROP INDEX IF EXISTS idx_project_expenses_project;
DROP INDEX IF EXISTS idx_project_tasks_project;
DROP INDEX IF EXISTS idx_projects_customer;
DROP INDEX IF EXISTS idx_projects_quotation;
DROP INDEX IF EXISTS idx_quotation_items_product;
DROP INDEX IF EXISTS idx_quotation_items_quotation;
DROP INDEX IF EXISTS idx_quotations_customer;
DROP INDEX IF EXISTS idx_quotations_deal;
DROP INDEX IF EXISTS idx_recipe_items_ingredient_product;
DROP INDEX IF EXISTS idx_sale_items_variant;
DROP INDEX IF EXISTS idx_sales_created_by;
DROP INDEX IF EXISTS idx_sales_customer;
DROP INDEX IF EXISTS idx_shifts_opened_by;
DROP INDEX IF EXISTS idx_stock_movements_product;
DROP INDEX IF EXISTS idx_stock_movements_variant;
DROP INDEX IF EXISTS idx_stock_opname_items_product;
DROP INDEX IF EXISTS idx_stock_transfer_items_product;
DROP INDEX IF EXISTS idx_stocks_product;
DROP INDEX IF EXISTS idx_subscription_invoices_subscription;
DROP INDEX IF EXISTS idx_subscription_refunds_tenant;
DROP INDEX IF EXISTS idx_subscriptions_plan;
DROP INDEX IF EXISTS idx_user_outlets_user;
DROP INDEX IF EXISTS idx_visits_customer;
DROP INDEX IF EXISTS idx_visits_sale;
ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_role;
ALTER TABLE users
  ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT;
